# Generated by Django 5.1.2 on 2024-10-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.CharField(default="biba", max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
