# Generated by Django 5.1.2 on 2024-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurator", "0002_question_answer_delete_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="package",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("completed", "Completed")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
