# Generated by Django 5.1.2 on 2024-11-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_package_last_modified_package_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='package',
            new_name='package_id',
        ),
    ]
