# Generated by Django 5.1.2 on 2024-11-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0004_rename_package_tag_package_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='theme',
            new_name='theme_id',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='package',
            new_name='package_id',
        ),
        migrations.RenameField(
            model_name='round',
            old_name='name',
            new_name='round',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_names',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='round',
            new_name='round_id',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='name',
            new_name='theme',
        ),
    ]
